### ISSUE TITLE
Small typo on “Principles: Any Technology Will Do”

### ISSUE THREAD

**Issue by beep** [piccalil-li/cube-css-issue-tracker#2]
Just spotted a tiny typo under https://piccalil.li/cube-css/principles/#heading-any-technology-will-do:

> Wether you like to author your CSS with Sass, Less, PostCSS, or even CSS-in-JS: the principles and methodology of CUBE CSS remain.

(“Wether” s/b “Whether”.)

Thanks for a wonderful resource, @hankchizljaw. Really enjoying it so far, and I’m excited to finish reading it.

**Comment by beep** [comment]
(Just noticed the same on https://piccalil.li/cube-css/grouping/#heading-consistency-is-the-aim.)

(I will stop spamming you now hi, thank you again)

**Comment by Andy-set-studio** [comment]
Thanks, Ethan I am terrible at using correct words so this is very helpful! 

(glad you are enjoying it ♥️)

**Comment by beep** [comment]
> I am terrible at using correct words

uh this is _literally me_

Seriously, it’s wonderful Andy. Thank you.

**Comment by Andy-set-studio** [comment]
This is all sorted. Thanks again!
