### ISSUE TITLE
Flow utility link goes to localhost:8080

### ISSUE THREAD

**Issue by geoffrich** [piccalil-li/cube-css-issue-tracker#3]
The flow utility link in the second paragraph of the [Composition within blocks section](https://piccalil.li/cube-css/block/#heading-composition-within-blocks) goes to http://localhost:8080/cube-css/composition/#heading-examples. I assume it should go to https://piccalil.li/cube-css/composition/#heading-examples instead.

Loving the guide so far!

**Comment by Andy-set-studio** [comment]
Ah whoops! I’ll grab that, thanks 🙂

**Comment by Andy-set-studio** [comment]
This is all sorted. Thanks again!
