### ISSUE TITLE
404 broken link at: Examples / Learning Resources / Dashboard

### ISSUE THREAD

**Issue by gitbreaker222** [piccalil-li/cube-css-issue-tracker#6]
at https://cube.fyi/examples/#heading-learning-resources

the second link to https://cube.fyi/tutorial/build-a-dashboard-with-cube-css/

its a 404

**Comment by ZediWards** [comment]
Issue:
![image](https://user-images.githubusercontent.com/33021719/106222952-87792780-61ae-11eb-85a3-1d3c07b32be1.png)
This link direct you to a 404: https://cube.fyi/tutorial/build-a-dashboard-with-cube-css/
Solution:
It seems like the link should be pointing to the tutorial on the Piccalilli site: https://piccalil.li/tutorial/build-a-dashboard-with-cube-css

**Comment by Andy-set-studio** [comment]
Thanks, both! That's fixed now :)
