### ISSUE TITLE
Correcting a Typo on the cube.fyi start page

### ISSUE THREAD

**Issue by wohfab** [piccalil-li/cube-css-issue-tracker#7]
On the last paragraph "[A high-level overview](https://cube.fyi/#heading-a-high-level-overview)", there is an "**is**" missing.

> [...] gives a high-level overview of what CUBE CSS \_\_is\_\_ and how it works [...]

Thank you for your incredible work, Andy!

**Comment by Andy-set-studio** [comment]
Ah thank you for that! I've just deployed a fix :)
